### PR TITLE
chore: update devfile's command; update base image

### PR DESCRIPTION
**Pull request by svor**
- After changing the collection's directory, we have to update `workingDir` attribute for devfile's commands.

- Added a few more commands to do all steps from README:
 1.Molecule: start a test pod for the automation
 2.Molecule: view the test instance that was created
 3.Molecule: run the verification against the test pod
 4.Molecule: apply the role to the pod
 5.Molecule: reset the test pod back to a fresh instance
 6.Molecule: run the full molecule test

- Fixed base ansible/creator-ee:v0.21.0 image reference

A short demo with the result: https://drive.google.com/file/d/1_2yLj6zXgOWDkk8sHN9LsJ3ro776lIHD/view?usp=sharing

### CODE REVIEW

**Comment by svor** [comment]
@brady-spiva @brandor5 
This is a PR to update your changes in PR https://github.com/devspaces-samples/ansible-devspaces-demo/pull/14

If it looks good to you, please merge and then we'll merge the main one

**Review by brandor5 — COMMENTED** [review]
@svor Hey, quick question. Why are we including all the extra steps in devfile.yml? `molecule test` covers all the commands you're running.

I'm not familiar with dev spaces so I'm probably missing something.

Thanks!

**Comment by svor** [comment]
Hello @brandor5, I've just added all steps that described in [README](https://github.com/devspaces-samples/ansible-devspaces-demo/blob/devspaces-3-rhel-8/README.md#to-begin-development-against-the-backup_file-role), I think it'll help users follow these steps one by one.

Of course if it's needed an user can use only `molecule test` command that runs all scenarios.

**Comment by brandor5** [comment]
Thanks @svor, that makes sense to me.

@brady-spiva I'm good with these changes so feel free to merge unless you have an issue.

Thanks!

**Review by brady-spiva — APPROVED** [review]

**Comment by brady-spiva** [comment]
Thank you for reviewing, @brandor5 ! Merged!

**Pull request merged**
